"""Phase 2.2 acceptance gate: real Gemma-4-E4B K/V fixture.

Final Phase-2 → 3 gate. Validates the v2.1 kernel against
``reference_e8_attention`` on K/V tensors captured from a real
``google/gemma-4-E4B-it`` forward pass via
``tests/fixtures/capture_gemma4_kv.py``.

Tests two layer types:
- ``sliding_layer`` (layer 0): head_dim=256, num_kv=2, sliding_window=512.
- ``full_layer`` (layer 5): head_dim=512, num_kv=2, no sliding.

Env-gated: ``pytest.skip`` unless the fixture file is present at the
cache path (``~/.cache/glq/gemma4_e4b_kv_<hash>.pt``). The fixture is
generated by running ``tests/fixtures/capture_gemma4_kv.py`` once
(needs HF_TOKEN if the Gemma-4 weights aren't already cached locally).
The test passes ``rtol=5e-3, atol=5e-3`` against the reference.
"""
from __future__ import annotations

import math
import os
from pathlib import Path

import pytest
import torch


pytestmark = pytest.mark.skipif(
    not torch.cuda.is_available(),
    reason="Triton kernels require CUDA",
)


# ── fixture loader ──────────────────────────────────────────────────


def _find_fixture() -> Path | None:
    """Locate a cached Gemma-4-E4B K/V fixture; return None if missing."""
    cache_dir = Path.home() / ".cache" / "glq"
    if not cache_dir.exists():
        return None
    matches = sorted(cache_dir.glob("gemma4_e4b_kv_*.pt"))
    return matches[0] if matches else None


@pytest.fixture(scope="module")
def gemma4_kv():
    """Load the cached Gemma-4-E4B K/V fixture or skip the module."""
    path = _find_fixture()
    if path is None:
        pytest.skip(
            "No Gemma-4-E4B K/V fixture found in ~/.cache/glq/. "
            "Run `python tests/fixtures/capture_gemma4_kv.py` first "
            "(needs HF_TOKEN + ~5 minutes for the model download)."
        )
    return torch.load(path, map_location="cpu", weights_only=False)


@pytest.fixture(scope="module")
def quantizer_4bpw():
    from glq.codebook import E8ShellCodebook
    from glq.kv_e8 import E8KVQuantizer
    cb = E8ShellCodebook(verbose=False)
    for name in ("codebook", "codebook_norms", "codebook_half",
                 "codebook_half_t", "codebook_norms_half",
                 "codebook_packed"):
        setattr(cb, name, getattr(cb, name).to("cuda"))
    cb.device = "cuda"
    return E8KVQuantizer(cb, n_stages=2, secondary_stages=0)


@pytest.fixture(scope="module")
def hadamard_8():
    from glq_vllm.e8_paged_cache import _get_hadamard
    return _get_hadamard(torch.float32, "cuda")


def _quantize_to_paged(K, V, quantizer, *, num_blocks, block_size):
    Tk, H_kv, D = K.shape
    n_groups = D // 8

    qk = quantizer.quantize(K)
    qv = quantizer.quantize(V)

    def _pack_int16(qt_idx):
        flat = qt_idx.reshape(Tk, H_kv, n_groups).contiguous()
        paged = torch.zeros(
            num_blocks, block_size, H_kv, n_groups,
            dtype=torch.int16, device=K.device,
        )
        for t in range(Tk):
            paged[t // block_size, t % block_size] = flat[t]
        return paged

    def _pack_scale(scale_tensor):
        flat = scale_tensor.reshape(Tk, H_kv, n_groups).contiguous()
        paged = torch.zeros(
            num_blocks, block_size, H_kv, n_groups,
            dtype=flat.dtype, device=K.device,
        )
        for t in range(Tk):
            paged[t // block_size, t % block_size] = flat[t]
        return paged

    return (
        _pack_int16(qk["idx1"]), _pack_int16(qk["idx2"]),
        _pack_scale(qk["scale"]),
        _pack_int16(qv["idx1"]), _pack_int16(qv["idx2"]),
        _pack_scale(qv["scale"]),
        qk, qv,
    )


def _run_kernel(q, k_idx1, k_idx2, k_scale, v_idx1, v_idx2, v_scale,
                codebook, H_mat, resid_scale, *, Tk, softmax_scale,
                sliding_window):
    from glq_vllm.triton_unified_attention_e8 import (
        unified_attention_e8_v2_1,
    )
    Tq = q.shape[0]
    num_blocks = k_idx1.shape[0]
    out = torch.zeros_like(q)
    cu_seqlens_q = torch.tensor([0, Tq], device=q.device, dtype=torch.int32)
    seqused_k = torch.tensor([Tk], device=q.device, dtype=torch.int32)
    block_table = torch.arange(
        num_blocks, device=q.device, dtype=torch.int32
    ).reshape(1, num_blocks)
    unified_attention_e8_v2_1(
        q=q,
        k_idx1=k_idx1, k_idx2=k_idx2, k_scale=k_scale,
        v_idx1=v_idx1, v_idx2=v_idx2, v_scale=v_scale,
        codebook=codebook, H_mat=H_mat,
        out=out,
        cu_seqlens_q=cu_seqlens_q,
        seqused_k=seqused_k,
        softmax_scale=softmax_scale,
        resid_scale=resid_scale,
        block_table=block_table,
        sliding_window=sliding_window,
    )
    return out


def _check_layer(layer_data, quantizer, codebook, hadamard_8):
    """Run kernel vs reference on one captured layer, return diagnostics."""
    K_real = layer_data["k"].to("cuda")        # [seq, num_kv, head_dim] fp16
    V_real = layer_data["v"].to("cuda")
    num_q_heads = layer_data["num_q_heads"]
    num_kv_heads = layer_data["num_kv_heads"]
    head_dim = layer_data["head_dim"]
    sliding_window = layer_data["sliding_window"]
    Tk = K_real.shape[0]
    Tq = Tk    # prefill-shaped (matches reference causal convention)
    block_size = 16
    num_blocks = (Tk + block_size - 1) // block_size

    # Build random Q at the right shape (test only validates K/V dequant).
    g = torch.Generator(device="cuda").manual_seed(layer_data["layer_idx"])
    q = torch.randn(
        Tq, num_q_heads, head_dim,
        device="cuda", dtype=torch.float16, generator=g,
    )

    # Right-pad K/V if Tk doesn't fill the last block (paged layout).
    pad = num_blocks * block_size - Tk
    if pad > 0:
        K_padded = torch.cat([
            K_real,
            torch.zeros(pad, num_kv_heads, head_dim,
                        device="cuda", dtype=torch.float16),
        ], dim=0)
        V_padded = torch.cat([
            V_real,
            torch.zeros(pad, num_kv_heads, head_dim,
                        device="cuda", dtype=torch.float16),
        ], dim=0)
    else:
        K_padded = K_real
        V_padded = V_real

    (k_idx1, k_idx2, k_scale, v_idx1, v_idx2, v_scale,
     qk, qv) = _quantize_to_paged(
        K_padded, V_padded, quantizer,
        num_blocks=num_blocks, block_size=block_size,
    )
    # Slice the qt dicts back to the un-padded length so the reference
    # sees the same K/V the kernel does (kernel masks past max_seq_prefix).
    n_groups = head_dim // 8

    def _slice_qt(qt):
        return {
            "idx1": qt["idx1"].reshape(num_blocks * block_size, num_kv_heads,
                                      n_groups)[:Tk]
                    .reshape(-1, n_groups),
            "idx2": qt["idx2"].reshape(num_blocks * block_size, num_kv_heads,
                                      n_groups)[:Tk]
                    .reshape(-1, n_groups),
            "scale": qt["scale"].reshape(num_blocks * block_size,
                                        num_kv_heads, n_groups)[:Tk]
                     .reshape(Tk * num_kv_heads, n_groups),
            "shape": (Tk, num_kv_heads, head_dim),
            "dtype": qt["dtype"],
        }

    qk_ref = _slice_qt(qk)
    qv_ref = _slice_qt(qv)

    softmax_scale = 1.0 / math.sqrt(head_dim)

    from tests.test_e8_attention_reference import reference_e8_attention
    out_ref = reference_e8_attention(
        q, qk_ref, qv_ref, quantizer,
        causal=True, softmax_scale=softmax_scale,
        sliding_window=(sliding_window if sliding_window > 0 else None),
    )
    out_fk = _run_kernel(
        q, k_idx1, k_idx2, k_scale, v_idx1, v_idx2, v_scale,
        codebook, hadamard_8, float(quantizer.codebook.resid_scale),
        Tk=Tk, softmax_scale=softmax_scale,
        sliding_window=sliding_window,
    )

    max_abs = (out_ref.float() - out_fk.float()).abs().max().item()
    rmse = (out_ref.float() - out_fk.float()).pow(2).mean().sqrt().item()
    return max_abs, rmse, Tk


# ── tests ───────────────────────────────────────────────────────────


def test_phase_2_2_real_sliding_layer(gemma4_kv, quantizer_4bpw, hadamard_8):
    """Layer 0: real Gemma-4-E4B sliding-window K/V (head_dim=256, SW=512)."""
    layer = gemma4_kv["sliding_layer"]
    assert layer["is_sliding"], "expected sliding_attention layer"
    assert layer["head_dim"] == 256
    assert layer["sliding_window"] == 512

    codebook = quantizer_4bpw.codebook.codebook_half
    max_abs, rmse, Tk = _check_layer(layer, quantizer_4bpw, codebook, hadamard_8)
    print(f"  Sliding (layer {layer['layer_idx']}, H={layer['head_dim']}, "
          f"KV={layer['num_kv_heads']}, SW={layer['sliding_window']}, "
          f"Tk={Tk}): max-abs={max_abs:.2e} RMSE={rmse:.2e}")
    assert max_abs < 5e-3, (
        f"sliding layer max-abs={max_abs:.2e} >= 5e-3 (RMSE={rmse:.2e})"
    )


def test_phase_2_2_real_full_layer(gemma4_kv, quantizer_4bpw, hadamard_8):
    """Layer 5: real Gemma-4-E4B full-attention K/V (head_dim=512, no SW)."""
    layer = gemma4_kv["full_layer"]
    assert not layer["is_sliding"], "expected full_attention layer"
    assert layer["head_dim"] == 512
    assert layer["sliding_window"] == 0

    codebook = quantizer_4bpw.codebook.codebook_half
    max_abs, rmse, Tk = _check_layer(layer, quantizer_4bpw, codebook, hadamard_8)
    print(f"  Full    (layer {layer['layer_idx']}, H={layer['head_dim']}, "
          f"KV={layer['num_kv_heads']}, SW=0, Tk={Tk}): "
          f"max-abs={max_abs:.2e} RMSE={rmse:.2e}")
    assert max_abs < 5e-3, (
        f"full layer max-abs={max_abs:.2e} >= 5e-3 (RMSE={rmse:.2e})"
    )
