"""CPU-only tests for report (markdown tables) + store (local git roundtrip)."""
from __future__ import annotations

import subprocess

from glq.bench import report, store
from glq.bench import (
    BenchmarkResult,
    BenchRecord,
    HardwareMeta,
    ModelMeta,
    ServingMeta,
    ThroughputResult,
)


def _baseline():
    return BenchRecord(
        model=ModelMeta(id="org/M", quant_method="none"),
        benchmark=BenchmarkResult("mmlu_pro", "accuracy", 0.85, standardized=True),
        serving=ServingMeta(load_gpu_mem_gib=57.9),
        hardware=HardwareMeta(gpu_model="RTX PRO 6000"),
        timestamp_utc="2026-06-20T00:00:00Z")


def _glq():
    return BenchRecord(
        model=ModelMeta(id="xv/M-GLQ", base_model="org/M", quant_method="glq", bpw=5.0),
        benchmark=BenchmarkResult("mmlu_pro", "accuracy", 0.90, standardized=True),
        serving=ServingMeta(load_gpu_mem_gib=16.5),
        throughput=ThroughputResult(output_tok_s=69.0),
        hardware=HardwareMeta(gpu_model="RTX PRO 6000"),
        timestamp_utc="2026-06-20T00:00:00Z")


def test_index_table():
    t = report.index_table([_baseline(), _glq()])
    assert "Quality index (% of bf16 baseline)" in t
    assert "xv/M-GLQ" in t and "org/M" in t
    assert "105.9%" in t              # 0.90/0.85 retention
    assert "16.5" in t and "69" in t  # VRAM + tok/s columns


def test_perf_table_and_filter():
    recs = [_baseline(), _glq()]
    pt = report.perf_table(recs)
    assert "85.0%" in pt and "90.0%" in pt and "mmlu_pro" in pt
    only_glq = report.perf_table(recs, filters={"quant_method": "glq"})
    assert "xv/M-GLQ" in only_glq and "org/M" not in only_glq


def test_compare_table():
    ct = report.compare_table([_baseline(), _glq()],
                              models=["org/M", "xv/M-GLQ"], tasks=["mmlu_pro"])
    assert "90.0%" in ct and "85.0%" in ct and "16.5" in ct and "57.9" in ct


def test_store_append_and_load_local(tmp_path):
    repo = tmp_path / "results"
    repo.mkdir()
    subprocess.run(["git", "init"], cwd=repo, capture_output=True, check=True)
    recs = [_glq(), _baseline()]
    store.append(recs, str(repo))
    # records land under records/<base>/<model>.jsonl
    assert (repo / "records" / "org__M" / "xv__M-GLQ.jsonl").exists()
    assert (repo / "records" / "org__M" / "org__M.jsonl").exists()
    got = store.load_all(str(repo), sync=False)
    assert {g.model.id for g in got} == {"xv/M-GLQ", "org/M"}


def _glq_task(task, value):
    return BenchRecord(
        model=ModelMeta(id="xv/M-GLQ", base_model="org/M", quant_method="glq", bpw=5.0),
        benchmark=BenchmarkResult(task, "accuracy", value, standardized=True),
        timestamp_utc="2026-06-20T00:00:00Z")


def test_store_append_multi_task_per_model_and_idempotent(tmp_path):
    # Regression: multiple records for ONE model.id (different tasks) must all
    # survive — they share a destination file and must not overwrite each other.
    repo = tmp_path / "results"
    repo.mkdir()
    subprocess.run(["git", "init"], cwd=repo, capture_output=True, check=True)
    recs = [_glq_task("mmlu_pro", 0.90), _glq_task("aime_2024", 0.83),
            _glq_task("aime_2026", 0.80)]
    store.append(recs, str(repo))
    got = store.load_all(str(repo), sync=False)
    assert {g.benchmark.task for g in got} == {"mmlu_pro", "aime_2024", "aime_2026"}
    # Re-appending the same records is idempotent (dedup on exact JSON).
    store.append(recs, str(repo))
    got2 = store.load_all(str(repo), sync=False)
    assert len(got2) == 3


def test_leaderboard_renders():
    md = report.leaderboard([_baseline(), _glq()], generated_utc="2026-06-20T00:00:00Z")
    assert md.startswith("# GLQ benchmark leaderboard")
    assert "Auto-generated by `glq-bench`" in md
    assert "Quality index (% of bf16 baseline)" in md   # embedded index table
    assert "## org/M" in md                              # per-base section
    assert "105.9%" in md                                # retention carried through
